//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAD_ROTIKITA
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbundle
    {
        public string kode_dbundle { get; set; }
        public string kode_bundle { get; set; }
        public string kode_roti { get; set; }
        public Nullable<int> harga_roti { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual hbundle hbundle { get; set; }
        public virtual roti roti { get; set; }
    }
}
