//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAD_ROTIKITA
{
    using System;
    using System.Collections.Generic;
    
    public partial class htran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public htran()
        {
            this.dtrans = new HashSet<dtran>();
            this.transDiskons = new HashSet<transDiskon>();
        }
    
        public string htrans_id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> subtotal { get; set; }
        public Nullable<int> total_item { get; set; }
        public Nullable<int> total_diskon { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtran> dtrans { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transDiskon> transDiskons { get; set; }
    }
}
