//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAD_ROTIKITA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jenis_roti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jenis_roti()
        {
            this.buangs = new HashSet<buang>();
            this.rotis = new HashSet<roti>();
        }
    
        public string kode_jenis { get; set; }
        public string nama { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> harga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buang> buangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roti> rotis { get; set; }
    }
}
